# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches:
    - "master"
    - "develop"
  pull_request:
    branches:
    - "master"
    - "develop"

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./DapperMappers

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET 9.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: List installed .NET SDKs
      run: dotnet --list-sdks
      
    - name: Display dotnet version
      run: dotnet --version
    
    - name: Build the project
      run: dotnet build --configuration Release
      working-directory: ${{env.working-directory}}
      
    - name: Run test
      run: dotnet test --configuration Release --no-build --verbosity normal
      working-directory: ${{env.working-directory}}

